version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/tmp/techbank"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/tmp/techbank/kafka" 
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 
    depends_on:
      - zookeeper

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/tmp/techbank/mongo"
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
    environment:
      - MONGO_INITDB_DATABASE=bankAccount
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Pa$$w0rd

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Pa$$w0rd
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes: 
      - "mysql_data:/tmp/techbank/mysql" 
    environment:
      - MYSQL_USER=techbank
      - MYSQL_PASSWORD=techbank
      - MYSQL_ROOT_PASSWORD=Pa$$w0rd
      - MYSQL_DATABASE=bankAccount

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"
    environment:
      -   ADMINER_DEFAULT_SERVER=mysql                
 
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
  mysql_data:
    driver: local    
   
networks:
  default:
    external:
      name: techbankNet
      
