server:
  port: 5001

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
    username: techbank
    password: techbank
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankAccountConsumer
      auto-offset-reset: earliest
      # Configures the Spring Kafka ErrorHandlingDeserializer that delegates to the 'real' deserializers
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
          # Delegate deserializers
          deserializer:
              key:
                delegate:
                  class: org.apache.kafka.common.serialization.StringDeserializer
              value:
                delegate:
                  class: org.springframework.kafka.support.serializer.JsonDeserializer